LOCALIZATION_KURI_DPS = {}

local LOCALE = GetLocale()

if LOCALE == "frFR" then
	LOCALIZATION_KURI_DPS["PrimalBlessing"] = "Bénédiction primordiale"
	LOCALIZATION_KURI_DPS["DiamondFlaskEffect"] = "Flasque de diamant"
	LOCALIZATION_KURI_DPS["DiamondFlask"] = "Flacon de diamant"
	LOCALIZATION_KURI_DPS["MightyRage"] = "Rage puissante"
	LOCALIZATION_KURI_DPS["MightyRagePotion"] = "Potion de rage puissante"
	LOCALIZATION_KURI_DPS["Flurry"] = "Rafale"
	LOCALIZATION_KURI_DPS["ElixirGiants"] = "Elixir des géants"
	LOCALIZATION_KURI_DPS["ElixirGiantsPotion"] = "Elixir des géants"
	LOCALIZATION_KURI_DPS["ElixirMongoose"] = "Elixir de la Mangouste"
	LOCALIZATION_KURI_DPS["JujuPower"] = "Pouvoir de Juju"
	LOCALIZATION_KURI_DPS["CloudkeeperLegplates"] = "Jambières du Gardien des nuages"
	LOCALIZATION_KURI_DPS["HeavenBlessing"] = "Bénédiction céleste"
	LOCALIZATION_KURI_DPS["Overpower"] = "Fulgurance"
	LOCALIZATION_KURI_DPS["Recklessness"] = "Témérité"
	LOCALIZATION_KURI_DPS["LimitedInvulnerabilityPotion"] = "Potion d'invulnérabilité limitée"
	LOCALIZATION_KURI_DPS["Invulnerability"] = "Invulnérabilité"
	LOCALIZATION_KURI_DPS["GiftArthas"] = "Don d\'Arthas"
else
	LOCALIZATION_KURI_DPS["PrimalBlessing"] = "Primal Blessing"
	LOCALIZATION_KURI_DPS["DiamondFlaskEffect"] = "Diamond Flask"
	LOCALIZATION_KURI_DPS["DiamondFlask"] = "Diamond Flask"
	LOCALIZATION_KURI_DPS["MightyRage"] = "Mighty Rage"
	LOCALIZATION_KURI_DPS["MightyRagePotion"] = "Mighty Rage Potion"
	LOCALIZATION_KURI_DPS["Flurry"] = "Flurry"
	LOCALIZATION_KURI_DPS["ElixirGiantsPotion"] = "Elixir of Giants"
	LOCALIZATION_KURI_DPS["ElixirGiants"] = "Elixir of the Giants"
	LOCALIZATION_KURI_DPS["ElixirMongoose"] = "Elixir of the Mongoose"
	LOCALIZATION_KURI_DPS["JujuPower"] = "Juju Power"
	LOCALIZATION_KURI_DPS["CloudkeeperLegplates"] = "Cloudkeeper Legplates"
	LOCALIZATION_KURI_DPS["HeavenBlessing"] = "Heaven\'s Blessing"
	LOCALIZATION_KURI_DPS["Overpower"] = "Overpower"
	LOCALIZATION_KURI_DPS["Recklessness"] = "Recklessness"
	LOCALIZATION_KURI_DPS["LimitedInvulnerabilityPotion"] = "Limited Invulnerability Potion"
	LOCALIZATION_KURI_DPS["Invulnerability"] = "Invulnerability"
	LOCALIZATION_KURI_DPS["GiftArthas"] = "Gift of Arthas"
end